- id: '1573643274171'
  alias: Check Temperature
  description: 'Turn off stove in case of being left working when not in use '
  trigger:
  - above: '50'
    entity_id: sensor.dht_sensor_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: switch.stove
    service: switch.turn_off
- id: '1583842060799'
  alias: Alarm when smoke an flame are detected
  description: Turn off the stove if smoke and flame are detected
  trigger:
  - entity_id: switch.stove
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.motion_detection
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.smoke
        state: 'off'
      - condition: state
        entity_id: binary_sensor.flame_detection
        state: 'off'
  action:
  - data: {}
    entity_id: switch.stove
    service: switch.turn_off
  - data: {}
    entity_id: switch.kitchen_light
    service: switch.turn_on
  - data:
      entity_id: camera.kitchen_camera
      filename: /config/www/yourcamera_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg
    entity_id: camera.kitchen_camera
    service: camera.snapshot
  - data: {}
    entity_id: switch.buzzer
    service: switch.turn_on
- id: '1583848326639'
  alias: Turn on the kitchen light
  description: 'when human detected, turn on the light '
  trigger:
  - entity_id: binary_sensor.motion_detection
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.kitchen_light
    service: switch.turn_on
- id: '1583848383745'
  alias: Turn off the kitchen light
  description: after leaving kitchen about 1 minute, turn off the light
  trigger:
  - entity_id: binary_sensor.motion_detection
    for: 00:01:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.kitchen_light
    entity_id: switch.kitchen_light
    service: switch.turn_off
- id: '1583860054893'
  alias: Alarm when flame detected
  description: when flame is detected, stove is turned off no matter if someone is
    around
  trigger:
  - entity_id: binary_sensor.flame_detection
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: switch.stove
    service: switch.turn_off
  - data: {}
    entity_id: switch.kitchen_light
    service: switch.turn_on
  - data:
      entity_id: camera.kitchen_camera
      filename: /config/www/yourcamera_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg
    entity_id: camera.kitchen_camera
    service: camera.snapshot
  - data: {}
    entity_id: switch.buzzer
    service: switch.turn_on

